version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: rentcar
      POSTGRES_PASSWORD: rentcar_password
    ports:
      - "5440:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: