app:
  projet-l3-rent-car-prefix-url: http://localhost:8089
spring:
  application:
    name: projet-l3-rent-car
  security:
    enabled: false
  jackson:
    property-naming-strategy: SNAKE_CASE
    write_dates_as_timestamps: false
  profiles:
    active: ${SPRING_PROFILE:}
  datasource:
    url: jdbc:postgresql://localhost:5440/postgres
    username: rentcar
    password: rentcar_password
  flyway:
    locations: classpath:db/migration, classpath:db/local
    create-schemas: true
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      schema: rentcar

  jpa:
    open-in-view: true
    properties:
      jakarta.persistence.sharedCache.mode: UNSPECIFIED
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 500
          batch_versioned_data: true

springdoc:
  swagger-ui:
    tagsSorter: alpha
    disable-swagger-default-url: true
    urls-primary-name: internal

management:
  endpoint:
    health:
      probes:
        enabled: true
      group:
        liveness:
          include:
            - livenessState
            - db
        readiness:
          include:
            - readinessState
            - db
      show-details: when_authorized


server:

  port: 8089   # Ajoutez cette ligne pour spécifier le port
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024
  error:
    include-message: always
  http2:
    enabled: true


